In [ ]:
import numpy as np
np.array(['ab', 'cde', 'd'], dtype='<U2')
a = np.arange(12, dtype='i2').reshape(4,3)
print(a)
print(a.shape,a.ndim,a.dtype,a.itemsize,a.size)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3) 2 int16 2 12
